POST http://127.0.0.1:8000/accounts/login
Content-Type: application/json

{ "email": "felipe123@gmail.com", "password": "password" }

###

POST http://127.0.0.1:8000/accounts/cadastro
Content-Type: application/json

{ "first_name": "lucas", "last_name": "leite", "email": "felipe123@gmail.com", "password": "password" }

###

GET http://127.0.0.1:8000/accounts/usuario
Content-Type: application/json

{ }

###

POST http://127.0.0.1:8000/accounts/logout
Content-Type: application/json

{ "email": "lucas.leite5@aluno.senai.br", "password": "password" }

###

PATCH http://127.0.0.1:8000/accounts/update/
Content-Type: application/json
X-CSRFToken: 2KYd9j6fQakarZUqBsASYYhwDQZOPR9L


{ "email": "felipe123@gmail.com", "first_name": "Pedro" }