POST http://127.0.0.1:8000/accounts/login
Content-Type: application/json

{ "email": "usuariosuper@exemplo.com", "password": "senha_segura" }

###

POST http://127.0.0.1:8000/accounts/cadastro
Content-Type: application/json

{ "first_name": "lucas", "last_name": "leite", "email": "felipe1234566@gmail.com", "password": "password" }

###

GET http://127.0.0.1:8000/accounts/usuario
Content-Type: application/json

{ }

###

POST http://127.0.0.1:8000/accounts/logout
Content-Type: application/json

{ "email": "felipe12345@gmail.com", "password": "password" }

###

PATCH http://127.0.0.1:8000/accounts/update/
Content-Type: application/json
X-CSRFToken: xKKqSh1ofMq24EQHAgE6ioXC81W2PTnD


{ "email": "felipe1234566@gmail.com", "password": "pedro123456" }

###

POST http://127.0.0.1:8000/accounts/check/
Content-Type: application/json
X-CSRFToken: 2Wqc0QMN2nA62rqZcdEwnZvrOdxidDIH

{ "email":"felipe123@gmail.com", "password": "password" }

###

POST http://127.0.0.1:8000/accounts/cart/
Content-Type: application/json
X-CSRFToken: QMRkerEsJire1RxwxucDhQeCvT7mFx2m

{ "email":"usuariosuper@exemplo.com"}


### 


DELETE  http://127.0.0.1:8000/accounts/cart/
Content-Type: application/json
X-CSRFToken: Z7eWZFxOkaWQbkrBfkg2rb7eQ8sLV1bY

{ "email":"felipe12345@gmail.com", "product_id":"13"}



### 


PATCH  http://127.0.0.1:8000/accounts/cart/
Content-Type: application/json
X-CSRFToken: Z7eWZFxOkaWQbkrBfkg2rb7eQ8sLV1bY

{ "email":"felipe12345@gmail.com", "product_id":"12", "quantity": "12"}

###

POST http://127.0.0.1:8000/accounts/add-item/
Content-Type: application/json
X-CSRFToken: Z7eWZFxOkaWQbkrBfkg2rb7eQ8sLV1bY

{ "email":"felipe12345@gmail.com", "product_id": "12"}

###

POST http://127.0.0.1:8000/compra/compra-create/
Content-Type: application/json
X-CSRFToken: QMRkerEsJire1RxwxucDhQeCvT7mFx2m

{ "email":"usuariosuper@exemplo.com", "products":[16, 17], "quantity": [2,4], "valor_total":5000 }

###

POST http://127.0.0.1:8000/compra/compra-itens/
Content-Type: application/json
X-CSRFToken: QMRkerEsJire1RxwxucDhQeCvT7mFx2m

{ "email":"usuariosuper@exemplo.com", "pedido_id": 69 }
