POST http://127.0.0.1:8000/accounts/login
Content-Type: application/json

{ "email": "lucas.leite5@aluno.senai.br", "password": "password" }

###

POST http://127.0.0.1:8000/accounts/cadastro
Content-Type: application/json

{ "first_name": "lucas", "last_name": "leite", "email": "lucas.leite5@aluno.senai.br", "password": "password" }

###

GET http://127.0.0.1:8000/accounts/validar_token
Content-Type: application/json
Authorization: Token 2246a8b80a88ec5476ac472f210c6a374a414bc3

{ }